export const TaskActions = {
  LOAD_TODOS: 'LOAD_TODOS',
  ADD_TODO: 'ADD_TODO',
  TOGGLE_TODO_STATE: 'TOGGLE_TODO_STATE',
  EDIT_TODO: 'EDIT_TODO',
  TOGGLE_TODO_TO_BE_DELETED_STATE: 'TOGGLE_TODO_TO_BE_DELETED_STATE',
  DELETE_TODO_PERMANENTLY: 'DELETE_TODO_PERMANENTLY',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  REFRESH_TOKEN: 'REFRESH_TOKEN'
}
