export const AuthActions = {
  SET_AUTH_LOADING_STATE: 'SET_AUTH_LOADING_STATE',
  SET_NEW_ACCESS_TOKEN: 'SET_NEW_ACCESS_TOKEN',
  UPDATE_AUTH_STATE: 'UPDATE_AUTH_STATE',
  SET_AUTH_MESSAGE: 'SET_AUTH_MESSAGE'
}

export default AuthActions
